"""Every API operation declares the role-matrix rule(s) it is authorised by (role
matrix section 7: "a meta-test fails if any route has no rule"), and every rule
named here exists in the policy. The contract (docs/api/contract-phase1.md section 2)
is the source; keep this table in step with it."""

from __future__ import annotations

from app.authz import POLICY, Rule
from tests.test_contract_routes import CONTRACT

SIGNED_IN = "signed in"  # a session is enough; contents are filtered by view rules
PUBLIC = "public"  # no principal needed (sign-in methods, logout)

ROUTE_RULES: dict[str, tuple[str, ...]] = {
    "get_me": (SIGNED_IN,),
    "list_dev_users": (PUBLIC,),
    "dev_login": (PUBLIC,),
    "logout": (PUBLIC,),
    "search_users": ("user.search", "project.view"),
    "list_projects": ("project.view",),
    "create_project": ("project.create",),
    "get_project": ("project.view",),
    "update_project": ("project.edit_settings", "project.rename_status_labels"),
    "list_project_members": ("project.view",),
    "add_project_member": ("project.manage_members",),
    "update_project_member": ("project.manage_members",),
    "remove_project_member": ("project.manage_members",),
    "replace_rubric": ("project.edit_rubric",),
    "list_project_tags": ("project.view", "idea.view"),
    "list_ideas": ("project.view", "idea.view", "score.view_aggregate"),
    "get_board": ("project.view", "idea.view", "score.view_aggregate"),
    "create_idea": ("idea.create",),
    "get_idea": ("idea.view", "score.view_aggregate"),
    "update_idea": ("idea.edit_own", "idea.edit_any"),
    "delete_idea": ("idea.delete",),
    "change_idea_status": ("idea.change_status",),
    "set_idea_owner": ("idea.assign_owner", "idea.release_owner"),
    "volunteer_as_owner": ("idea.volunteer_owner",),
    "add_evaluators": ("evaluator.manage",),
    "remove_evaluator": ("evaluator.manage",),
    "set_evaluation_due_date": ("idea.set_due_date",),
    "close_evaluation": ("evaluation.close",),
    "reopen_evaluation": ("evaluation.close",),
    "list_evaluations": ("idea.view", "evaluation.view_others"),
    "get_my_evaluation": ("evaluation.view_own",),
    "save_my_evaluation": ("evaluation.submit_own",),
    "vote_idea": ("idea.vote",),
    "unvote_idea": ("idea.vote",),
    "watch_idea": ("idea.watch",),
    "unwatch_idea": ("idea.watch",),
    "list_idea_activity": ("idea.view",),
    "create_comment": ("comment.create",),
    "update_comment": ("comment.edit_own",),
    "delete_comment": ("comment.edit_own", "comment.delete_any"),
    "get_my_work": (SIGNED_IN, "idea.view", "score.view_aggregate"),
    "list_my_owned_ideas": (SIGNED_IN, "idea.view", "score.view_aggregate"),
    "global_search": (SIGNED_IN, "project.view", "idea.view"),
    # Phase 2 (docs/api/contract-phase2.md section 2)
    "get_auth_config": (PUBLIC,),
    "sso_login": (PUBLIC,),
    "sso_callback": (PUBLIC,),
    "break_glass_login": (PUBLIC,),
    "logout_redirect": (PUBLIC,),
    "list_admin_users": ("platform.manage_users",),
    "create_admin_user": ("platform.manage_users",),
    "get_admin_user": ("platform.manage_users",),
    "update_admin_user": ("platform.manage_users",),
    "replace_user_external_ids": ("platform.manage_users",),
    "unlink_user_identity": ("platform.manage_users",),
    "end_user_sessions": ("platform.manage_users",),
    "list_admin_groups": ("platform.manage_groups",),
    "create_group": ("platform.manage_groups",),
    "test_group_mapping": ("platform.manage_groups",),
    "get_group": ("platform.manage_groups",),
    "update_group": ("platform.manage_groups",),
    "delete_group": ("platform.manage_groups",),
    "replace_group_mapping": ("platform.manage_groups",),
    "list_group_members": ("platform.manage_groups",),
    "add_group_member": ("platform.manage_groups",),
    "remove_group_member": ("platform.manage_groups",),
    "search_groups": ("user.search",),
    "list_project_group_grants": ("project.view",),
    "add_project_group_grant": ("project.manage_members",),
    "update_project_group_grant": ("project.manage_members",),
    "remove_project_group_grant": ("project.manage_members",),
    "list_project_access": ("project.view",),
    "list_audit_entries": ("platform.view_audit_log",),
    "get_sso_config": ("platform.configure_sso",),
    # Phase 3 (docs/api/contract-phase3.md section 2)
    "list_notifications": (SIGNED_IN, "idea.view"),
    "get_notification_summary": (SIGNED_IN, "idea.view"),
    "mark_notification_read": (SIGNED_IN, "idea.view"),
    "mark_all_notifications_read": (SIGNED_IN, "idea.view"),
    "get_notification_preferences": ("self.manage_profile",),
    "update_notification_preferences": ("self.manage_profile",),
    "get_unsubscribe": ("self.unsubscribe",),
    "confirm_unsubscribe": ("self.unsubscribe",),
    "get_email_config": ("platform.configure_email",),
    "send_test_email": ("platform.configure_email",),
    "list_outbox_emails": ("platform.configure_email",),
    "retry_failed_outbox_emails": ("platform.configure_email",),
    "get_outbox_email": ("platform.configure_email",),
    "retry_outbox_email": ("platform.configure_email",),
    # Phase 4 (docs/api/contract-phase4.md section 2)
    "get_proposal": ("proposal.view", "proposal.write", "proposal.comment", "proposal.export"),
    "create_proposal": ("proposal.write",),
    "update_proposal_section": ("proposal.write",),
    "export_proposal_markdown": ("proposal.export", "score.view_aggregate"),
    "export_proposal_pdf": ("proposal.export", "score.view_aggregate"),
    "list_proposal_threads": ("proposal.view",),
    "create_proposal_thread": ("proposal.comment",),
    "reply_to_proposal_thread": ("proposal.comment",),
    "resolve_proposal_thread": ("proposal.comment",),
    "reopen_proposal_thread": ("proposal.comment",),
    "delete_proposal_comment": ("comment.edit_own", "comment.delete_any"),
    "get_public_project": ("public.submit",),
    "get_altcha_challenge": ("public.submit",),
    "submit_public_idea": ("public.submit",),
    "track_submission": ("public.track",),
    "set_submission_updates": ("public.track",),
    "resend_verification_email": ("public.track",),
    "erase_tracked_submission": ("public.track",),
    "verify_submission_email": ("public.track",),
    "get_public_form_settings": ("project.edit_settings",),
    "update_public_form_settings": ("project.edit_settings",),
    "list_moderation_queue": ("project.view", "idea.moderate"),
    "get_idea_submission": ("idea.view", "public.erase_submitter", "idea.moderate"),
    "approve_submission": ("idea.moderate",),
    "reject_submission": ("idea.moderate",),
    "erase_submitter": ("public.erase_submitter",),
    "get_branding": (PUBLIC,),
    "get_brand_asset": (PUBLIC,),
    "get_global_branding": ("platform.edit_branding",),
    "update_global_branding": ("platform.edit_branding",),
    "upload_global_brand_asset": ("platform.edit_branding",),
    "get_project_branding": ("project.edit_settings",),
    "update_project_branding": ("project.edit_settings",),
    "upload_project_brand_asset": ("project.edit_settings",),
    # Phase 5 (docs/api/contract-phase5.md section 2)
    "list_my_api_keys": ("api_key.manage_own",),
    "create_my_api_key": ("api_key.manage_own", "project.view"),
    "revoke_my_api_key": ("api_key.manage_own",),
    "list_admin_api_keys": ("api_key.manage_any",),
    "revoke_admin_api_key": ("api_key.manage_any",),
    "list_proposal_suggestions": (
        "proposal.view",
        "proposal.suggest_section",
        "proposal.write",
    ),
    "create_proposal_suggestion": ("proposal.suggest_section",),
    "accept_proposal_suggestion": ("proposal.write",),
    "discard_proposal_suggestion": ("proposal.write",),
    # Phase 6 (docs/api/contract-phase6.md section 2)
    "list_ai_agents": ("platform.manage_agents",),
    "register_ai_agent": ("platform.manage_agents",),
    "get_ai_agent": ("platform.manage_agents",),
    "update_ai_agent": ("platform.manage_agents",),
    "rotate_ai_agent_key": ("platform.manage_agents",),
    "test_ai_agent": ("platform.manage_agents",),
    "list_idea_ai_runs": (
        "idea.view",
        "ai.request_evaluation",
        "ai.research",
        "ai.draft_section",
        "ai.cancel_run",
        "evaluation.include_ai",
    ),
    "request_ai_evaluation": ("ai.request_evaluation",),
    "request_ai_research": ("ai.research",),
    "request_ai_section_draft": ("ai.draft_section",),
    "get_ai_run": ("idea.view",),
    "cancel_ai_run": ("ai.cancel_run",),
    "stream_ai_run_events": ("idea.view",),
    "set_evaluation_inclusion": ("evaluation.include_ai", "evaluation.view_others"),
    "get_research_note": ("idea.view",),
    "delete_research_note": ("ai.delete_note",),
    # Phase 7 (docs/api/contract-phase7.md section 2)
    "get_my_work_counts": (SIGNED_IN, "idea.view"),
    "list_my_evaluations_due": (SIGNED_IN, "idea.view"),
}


def test_every_operation_has_a_rule() -> None:
    assert set(ROUTE_RULES) == {operation_id for _, _, operation_id in CONTRACT}


def test_every_named_rule_is_in_the_policy() -> None:
    named = {rule for rules in ROUTE_RULES.values() for rule in rules} - {SIGNED_IN, PUBLIC}

    assert named <= {str(rule) for rule in POLICY}
    assert all(Rule(rule) in POLICY for rule in named)
