{{- $fullname := include "soundings.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "soundings.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.secretKey.existingSecret }}
  secret-key: {{ include "soundings.lookupOrGenerate" (dict "ctx" . "name" $fullname "key" "secret-key" "length" 64) }}
  {{- end }}
  {{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) .Values.externalDatabase.password }}
  database-password: {{ .Values.externalDatabase.password | b64enc }}
  {{- end }}
  {{- if and .Values.oidc.issuer (not .Values.oidc.existingSecret) .Values.oidc.clientSecret }}
  oidc-client-secret: {{ .Values.oidc.clientSecret | b64enc }}
  {{- end }}
  {{- if and .Values.smtp.host (not .Values.smtp.existingSecret) }}
  {{- with .Values.smtp.username }}
  smtp-username: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.smtp.password }}
  smtp-password: {{ . | b64enc }}
  {{- end }}
  {{- end }}
  {{- if and .Values.breakGlass.enabled (not .Values.breakGlass.existingSecret) }}
  break-glass-username: {{ "admin" | b64enc }}
  break-glass-password: {{ include "soundings.lookupOrGenerate" (dict "ctx" . "name" $fullname "key" "break-glass-password" "length" 24) }}
  {{- end }}
