/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DesignRouteImport } from './routes/design'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppIdeasIdeaKeyRouteImport } from './routes/_app/ideas.$ideaKey'
import { Route as AppPSlugRouteImport } from './routes/_app/p.$slug'
import { Route as AppPSlugIndexRouteImport } from './routes/_app/p.$slug.index'
import { Route as AppPSlugSettingsRouteImport } from './routes/_app/p.$slug.settings'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeasIdeaKeyRoute = AppIdeasIdeaKeyRouteImport.update({
  id: '/ideas/$ideaKey',
  path: '/ideas/$ideaKey',
  getParentRoute: () => AppRoute,
} as any)
const AppPSlugRoute = AppPSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppPSlugIndexRoute = AppPSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPSlugRoute,
} as any)
const AppPSlugSettingsRoute = AppPSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppPSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/design': typeof DesignRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/settings': typeof AppSettingsRoute
  '/ideas/$ideaKey': typeof AppIdeasIdeaKeyRoute
  '/p/$slug': typeof AppPSlugRouteWithChildren
  '/p/$slug/settings': typeof AppPSlugSettingsRoute
  '/p/$slug/': typeof AppPSlugIndexRoute
}
export interface FileRoutesByTo {
  '/design': typeof DesignRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/ideas/$ideaKey': typeof AppIdeasIdeaKeyRoute
  '/p/$slug/settings': typeof AppPSlugSettingsRoute
  '/p/$slug': typeof AppPSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/design': typeof DesignRoute
  '/login': typeof LoginRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/ideas/$ideaKey': typeof AppIdeasIdeaKeyRoute
  '/_app/p/$slug': typeof AppPSlugRouteWithChildren
  '/_app/p/$slug/settings': typeof AppPSlugSettingsRoute
  '/_app/p/$slug/': typeof AppPSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/login'
    | '/$'
    | '/settings'
    | '/ideas/$ideaKey'
    | '/p/$slug'
    | '/p/$slug/settings'
    | '/p/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/design'
    | '/login'
    | '/$'
    | '/settings'
    | '/'
    | '/ideas/$ideaKey'
    | '/p/$slug/settings'
    | '/p/$slug'
  id:
    | '__root__'
    | '/_app'
    | '/design'
    | '/login'
    | '/_app/$'
    | '/_app/settings'
    | '/_app/'
    | '/_app/ideas/$ideaKey'
    | '/_app/p/$slug'
    | '/_app/p/$slug/settings'
    | '/_app/p/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DesignRoute: typeof DesignRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ideas/$ideaKey': {
      id: '/_app/ideas/$ideaKey'
      path: '/ideas/$ideaKey'
      fullPath: '/ideas/$ideaKey'
      preLoaderRoute: typeof AppIdeasIdeaKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p/$slug': {
      id: '/_app/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof AppPSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p/$slug/': {
      id: '/_app/p/$slug/'
      path: '/'
      fullPath: '/p/$slug/'
      preLoaderRoute: typeof AppPSlugIndexRouteImport
      parentRoute: typeof AppPSlugRoute
    }
    '/_app/p/$slug/settings': {
      id: '/_app/p/$slug/settings'
      path: '/settings'
      fullPath: '/p/$slug/settings'
      preLoaderRoute: typeof AppPSlugSettingsRouteImport
      parentRoute: typeof AppPSlugRoute
    }
  }
}

interface AppPSlugRouteChildren {
  AppPSlugSettingsRoute: typeof AppPSlugSettingsRoute
  AppPSlugIndexRoute: typeof AppPSlugIndexRoute
}

const AppPSlugRouteChildren: AppPSlugRouteChildren = {
  AppPSlugSettingsRoute: AppPSlugSettingsRoute,
  AppPSlugIndexRoute: AppPSlugIndexRoute,
}

const AppPSlugRouteWithChildren = AppPSlugRoute._addFileChildren(
  AppPSlugRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppIdeasIdeaKeyRoute: typeof AppIdeasIdeaKeyRoute
  AppPSlugRoute: typeof AppPSlugRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppIdeasIdeaKeyRoute: AppIdeasIdeaKeyRoute,
  AppPSlugRoute: AppPSlugRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DesignRoute: DesignRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
