/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DesignRouteImport } from './routes/design'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TrackRouteImport } from './routes/track'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SlugSubmitRouteImport } from './routes/$slug.submit'
import { Route as SlugVerifyRouteImport } from './routes/$slug.verify'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppIdeasIdeaKeyRouteImport } from './routes/_app/ideas.$ideaKey'
import { Route as AppPSlugRouteImport } from './routes/_app/p.$slug'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings.index'
import { Route as AppSettingsAdminRouteImport } from './routes/_app/settings._admin'
import { Route as AppSettingsApiKeysRouteImport } from './routes/_app/settings.api-keys'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings.notifications'
import { Route as AppPSlugIndexRouteImport } from './routes/_app/p.$slug.index'
import { Route as AppPSlugReviewRouteImport } from './routes/_app/p.$slug.review'
import { Route as AppPSlugSettingsRouteImport } from './routes/_app/p.$slug.settings'
import { Route as AppSettingsAdminAllApiKeysRouteImport } from './routes/_app/settings._admin.all-api-keys'
import { Route as AppSettingsAdminAuditRouteImport } from './routes/_app/settings._admin.audit'
import { Route as AppSettingsAdminBrandingRouteImport } from './routes/_app/settings._admin.branding'
import { Route as AppSettingsAdminEmailRouteImport } from './routes/_app/settings._admin.email'
import { Route as AppSettingsAdminSsoRouteImport } from './routes/_app/settings._admin.sso'
import { Route as AppSettingsAdminUsersRouteImport } from './routes/_app/settings._admin.users'
import { Route as AppSettingsAdminGroupsIndexRouteImport } from './routes/_app/settings._admin.groups.index'
import { Route as AppSettingsAdminGroupsGroupIdRouteImport } from './routes/_app/settings._admin.groups.$groupId'
import { Route as AppSettingsAdminUsersUserIdRouteImport } from './routes/_app/settings._admin.users.$userId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugSubmitRoute = SlugSubmitRouteImport.update({
  id: '/$slug/submit',
  path: '/$slug/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugVerifyRoute = SlugVerifyRouteImport.update({
  id: '/$slug/verify',
  path: '/$slug/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeasIdeaKeyRoute = AppIdeasIdeaKeyRouteImport.update({
  id: '/ideas/$ideaKey',
  path: '/ideas/$ideaKey',
  getParentRoute: () => AppRoute,
} as any)
const AppPSlugRoute = AppPSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAdminRoute = AppSettingsAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppPSlugIndexRoute = AppPSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPSlugRoute,
} as any)
const AppPSlugReviewRoute = AppPSlugReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppPSlugRoute,
} as any)
const AppPSlugSettingsRoute = AppPSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppPSlugRoute,
} as any)
const AppSettingsAdminAllApiKeysRoute =
  AppSettingsAdminAllApiKeysRouteImport.update({
    id: '/all-api-keys',
    path: '/all-api-keys',
    getParentRoute: () => AppSettingsAdminRoute,
  } as any)
const AppSettingsAdminAuditRoute = AppSettingsAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppSettingsAdminRoute,
} as any)
const AppSettingsAdminBrandingRoute =
  AppSettingsAdminBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AppSettingsAdminRoute,
  } as any)
const AppSettingsAdminEmailRoute = AppSettingsAdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppSettingsAdminRoute,
} as any)
const AppSettingsAdminSsoRoute = AppSettingsAdminSsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => AppSettingsAdminRoute,
} as any)
const AppSettingsAdminUsersRoute = AppSettingsAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppSettingsAdminRoute,
} as any)
const AppSettingsAdminGroupsIndexRoute =
  AppSettingsAdminGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AppSettingsAdminRoute,
  } as any)
const AppSettingsAdminGroupsGroupIdRoute =
  AppSettingsAdminGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AppSettingsAdminRoute,
  } as any)
const AppSettingsAdminUsersUserIdRoute =
  AppSettingsAdminUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AppSettingsAdminUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/design': typeof DesignRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify': typeof VerifyRoute
  '/$slug/submit': typeof SlugSubmitRoute
  '/$slug/verify': typeof SlugVerifyRoute
  '/$': typeof AppSplatRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/ideas/$ideaKey': typeof AppIdeasIdeaKeyRoute
  '/p/$slug': typeof AppPSlugRouteWithChildren
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/p/$slug/review': typeof AppPSlugReviewRoute
  '/p/$slug/settings': typeof AppPSlugSettingsRoute
  '/settings/all-api-keys': typeof AppSettingsAdminAllApiKeysRoute
  '/settings/audit': typeof AppSettingsAdminAuditRoute
  '/settings/branding': typeof AppSettingsAdminBrandingRoute
  '/settings/email': typeof AppSettingsAdminEmailRoute
  '/settings/sso': typeof AppSettingsAdminSsoRoute
  '/settings/users': typeof AppSettingsAdminUsersRouteWithChildren
  '/p/$slug/': typeof AppPSlugIndexRoute
  '/settings/groups/$groupId': typeof AppSettingsAdminGroupsGroupIdRoute
  '/settings/users/$userId': typeof AppSettingsAdminUsersUserIdRoute
  '/settings/groups/': typeof AppSettingsAdminGroupsIndexRoute
}
export interface FileRoutesByTo {
  '/design': typeof DesignRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify': typeof VerifyRoute
  '/$slug/submit': typeof SlugSubmitRoute
  '/$slug/verify': typeof SlugVerifyRoute
  '/$': typeof AppSplatRoute
  '/notifications': typeof AppNotificationsRoute
  '/': typeof AppIndexRoute
  '/ideas/$ideaKey': typeof AppIdeasIdeaKeyRoute
  '/settings': typeof AppSettingsIndexRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/p/$slug/review': typeof AppPSlugReviewRoute
  '/p/$slug/settings': typeof AppPSlugSettingsRoute
  '/settings/all-api-keys': typeof AppSettingsAdminAllApiKeysRoute
  '/settings/audit': typeof AppSettingsAdminAuditRoute
  '/settings/branding': typeof AppSettingsAdminBrandingRoute
  '/settings/email': typeof AppSettingsAdminEmailRoute
  '/settings/sso': typeof AppSettingsAdminSsoRoute
  '/settings/users': typeof AppSettingsAdminUsersRouteWithChildren
  '/p/$slug': typeof AppPSlugIndexRoute
  '/settings/groups/$groupId': typeof AppSettingsAdminGroupsGroupIdRoute
  '/settings/users/$userId': typeof AppSettingsAdminUsersUserIdRoute
  '/settings/groups': typeof AppSettingsAdminGroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/design': typeof DesignRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify': typeof VerifyRoute
  '/$slug/submit': typeof SlugSubmitRoute
  '/$slug/verify': typeof SlugVerifyRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/ideas/$ideaKey': typeof AppIdeasIdeaKeyRoute
  '/_app/p/$slug': typeof AppPSlugRouteWithChildren
  '/_app/settings/_admin': typeof AppSettingsAdminRouteWithChildren
  '/_app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/p/$slug/review': typeof AppPSlugReviewRoute
  '/_app/p/$slug/settings': typeof AppPSlugSettingsRoute
  '/_app/settings/_admin/all-api-keys': typeof AppSettingsAdminAllApiKeysRoute
  '/_app/settings/_admin/audit': typeof AppSettingsAdminAuditRoute
  '/_app/settings/_admin/branding': typeof AppSettingsAdminBrandingRoute
  '/_app/settings/_admin/email': typeof AppSettingsAdminEmailRoute
  '/_app/settings/_admin/sso': typeof AppSettingsAdminSsoRoute
  '/_app/settings/_admin/users': typeof AppSettingsAdminUsersRouteWithChildren
  '/_app/p/$slug/': typeof AppPSlugIndexRoute
  '/_app/settings/_admin/groups/$groupId': typeof AppSettingsAdminGroupsGroupIdRoute
  '/_app/settings/_admin/users/$userId': typeof AppSettingsAdminUsersUserIdRoute
  '/_app/settings/_admin/groups/': typeof AppSettingsAdminGroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/login'
    | '/track'
    | '/unsubscribe'
    | '/verify'
    | '/$slug/submit'
    | '/$slug/verify'
    | '/$'
    | '/notifications'
    | '/settings'
    | '/ideas/$ideaKey'
    | '/p/$slug'
    | '/settings/api-keys'
    | '/settings/notifications'
    | '/settings/'
    | '/p/$slug/review'
    | '/p/$slug/settings'
    | '/settings/all-api-keys'
    | '/settings/audit'
    | '/settings/branding'
    | '/settings/email'
    | '/settings/sso'
    | '/settings/users'
    | '/p/$slug/'
    | '/settings/groups/$groupId'
    | '/settings/users/$userId'
    | '/settings/groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/design'
    | '/login'
    | '/track'
    | '/unsubscribe'
    | '/verify'
    | '/$slug/submit'
    | '/$slug/verify'
    | '/$'
    | '/notifications'
    | '/'
    | '/ideas/$ideaKey'
    | '/settings'
    | '/settings/api-keys'
    | '/settings/notifications'
    | '/p/$slug/review'
    | '/p/$slug/settings'
    | '/settings/all-api-keys'
    | '/settings/audit'
    | '/settings/branding'
    | '/settings/email'
    | '/settings/sso'
    | '/settings/users'
    | '/p/$slug'
    | '/settings/groups/$groupId'
    | '/settings/users/$userId'
    | '/settings/groups'
  id:
    | '__root__'
    | '/_app'
    | '/design'
    | '/login'
    | '/track'
    | '/unsubscribe'
    | '/verify'
    | '/$slug/submit'
    | '/$slug/verify'
    | '/_app/$'
    | '/_app/notifications'
    | '/_app/settings'
    | '/_app/'
    | '/_app/ideas/$ideaKey'
    | '/_app/p/$slug'
    | '/_app/settings/_admin'
    | '/_app/settings/api-keys'
    | '/_app/settings/notifications'
    | '/_app/settings/'
    | '/_app/p/$slug/review'
    | '/_app/p/$slug/settings'
    | '/_app/settings/_admin/all-api-keys'
    | '/_app/settings/_admin/audit'
    | '/_app/settings/_admin/branding'
    | '/_app/settings/_admin/email'
    | '/_app/settings/_admin/sso'
    | '/_app/settings/_admin/users'
    | '/_app/p/$slug/'
    | '/_app/settings/_admin/groups/$groupId'
    | '/_app/settings/_admin/users/$userId'
    | '/_app/settings/_admin/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DesignRoute: typeof DesignRoute
  LoginRoute: typeof LoginRoute
  TrackRoute: typeof TrackRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyRoute: typeof VerifyRoute
  SlugSubmitRoute: typeof SlugSubmitRoute
  SlugVerifyRoute: typeof SlugVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/submit': {
      id: '/$slug/submit'
      path: '/$slug/submit'
      fullPath: '/$slug/submit'
      preLoaderRoute: typeof SlugSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/verify': {
      id: '/$slug/verify'
      path: '/$slug/verify'
      fullPath: '/$slug/verify'
      preLoaderRoute: typeof SlugVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ideas/$ideaKey': {
      id: '/_app/ideas/$ideaKey'
      path: '/ideas/$ideaKey'
      fullPath: '/ideas/$ideaKey'
      preLoaderRoute: typeof AppIdeasIdeaKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p/$slug': {
      id: '/_app/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof AppPSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/_admin': {
      id: '/_app/settings/_admin'
      path: ''
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsAdminRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/api-keys': {
      id: '/_app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/p/$slug/': {
      id: '/_app/p/$slug/'
      path: '/'
      fullPath: '/p/$slug/'
      preLoaderRoute: typeof AppPSlugIndexRouteImport
      parentRoute: typeof AppPSlugRoute
    }
    '/_app/p/$slug/review': {
      id: '/_app/p/$slug/review'
      path: '/review'
      fullPath: '/p/$slug/review'
      preLoaderRoute: typeof AppPSlugReviewRouteImport
      parentRoute: typeof AppPSlugRoute
    }
    '/_app/p/$slug/settings': {
      id: '/_app/p/$slug/settings'
      path: '/settings'
      fullPath: '/p/$slug/settings'
      preLoaderRoute: typeof AppPSlugSettingsRouteImport
      parentRoute: typeof AppPSlugRoute
    }
    '/_app/settings/_admin/all-api-keys': {
      id: '/_app/settings/_admin/all-api-keys'
      path: '/all-api-keys'
      fullPath: '/settings/all-api-keys'
      preLoaderRoute: typeof AppSettingsAdminAllApiKeysRouteImport
      parentRoute: typeof AppSettingsAdminRoute
    }
    '/_app/settings/_admin/audit': {
      id: '/_app/settings/_admin/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAdminAuditRouteImport
      parentRoute: typeof AppSettingsAdminRoute
    }
    '/_app/settings/_admin/branding': {
      id: '/_app/settings/_admin/branding'
      path: '/branding'
      fullPath: '/settings/branding'
      preLoaderRoute: typeof AppSettingsAdminBrandingRouteImport
      parentRoute: typeof AppSettingsAdminRoute
    }
    '/_app/settings/_admin/email': {
      id: '/_app/settings/_admin/email'
      path: '/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof AppSettingsAdminEmailRouteImport
      parentRoute: typeof AppSettingsAdminRoute
    }
    '/_app/settings/_admin/sso': {
      id: '/_app/settings/_admin/sso'
      path: '/sso'
      fullPath: '/settings/sso'
      preLoaderRoute: typeof AppSettingsAdminSsoRouteImport
      parentRoute: typeof AppSettingsAdminRoute
    }
    '/_app/settings/_admin/users': {
      id: '/_app/settings/_admin/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsAdminUsersRouteImport
      parentRoute: typeof AppSettingsAdminRoute
    }
    '/_app/settings/_admin/groups/': {
      id: '/_app/settings/_admin/groups/'
      path: '/groups'
      fullPath: '/settings/groups/'
      preLoaderRoute: typeof AppSettingsAdminGroupsIndexRouteImport
      parentRoute: typeof AppSettingsAdminRoute
    }
    '/_app/settings/_admin/groups/$groupId': {
      id: '/_app/settings/_admin/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/settings/groups/$groupId'
      preLoaderRoute: typeof AppSettingsAdminGroupsGroupIdRouteImport
      parentRoute: typeof AppSettingsAdminRoute
    }
    '/_app/settings/_admin/users/$userId': {
      id: '/_app/settings/_admin/users/$userId'
      path: '/$userId'
      fullPath: '/settings/users/$userId'
      preLoaderRoute: typeof AppSettingsAdminUsersUserIdRouteImport
      parentRoute: typeof AppSettingsAdminUsersRoute
    }
  }
}

interface AppSettingsAdminUsersRouteChildren {
  AppSettingsAdminUsersUserIdRoute: typeof AppSettingsAdminUsersUserIdRoute
}

const AppSettingsAdminUsersRouteChildren: AppSettingsAdminUsersRouteChildren = {
  AppSettingsAdminUsersUserIdRoute: AppSettingsAdminUsersUserIdRoute,
}

const AppSettingsAdminUsersRouteWithChildren =
  AppSettingsAdminUsersRoute._addFileChildren(
    AppSettingsAdminUsersRouteChildren,
  )

interface AppSettingsAdminRouteChildren {
  AppSettingsAdminAllApiKeysRoute: typeof AppSettingsAdminAllApiKeysRoute
  AppSettingsAdminAuditRoute: typeof AppSettingsAdminAuditRoute
  AppSettingsAdminBrandingRoute: typeof AppSettingsAdminBrandingRoute
  AppSettingsAdminEmailRoute: typeof AppSettingsAdminEmailRoute
  AppSettingsAdminSsoRoute: typeof AppSettingsAdminSsoRoute
  AppSettingsAdminUsersRoute: typeof AppSettingsAdminUsersRouteWithChildren
  AppSettingsAdminGroupsGroupIdRoute: typeof AppSettingsAdminGroupsGroupIdRoute
  AppSettingsAdminGroupsIndexRoute: typeof AppSettingsAdminGroupsIndexRoute
}

const AppSettingsAdminRouteChildren: AppSettingsAdminRouteChildren = {
  AppSettingsAdminAllApiKeysRoute: AppSettingsAdminAllApiKeysRoute,
  AppSettingsAdminAuditRoute: AppSettingsAdminAuditRoute,
  AppSettingsAdminBrandingRoute: AppSettingsAdminBrandingRoute,
  AppSettingsAdminEmailRoute: AppSettingsAdminEmailRoute,
  AppSettingsAdminSsoRoute: AppSettingsAdminSsoRoute,
  AppSettingsAdminUsersRoute: AppSettingsAdminUsersRouteWithChildren,
  AppSettingsAdminGroupsGroupIdRoute: AppSettingsAdminGroupsGroupIdRoute,
  AppSettingsAdminGroupsIndexRoute: AppSettingsAdminGroupsIndexRoute,
}

const AppSettingsAdminRouteWithChildren =
  AppSettingsAdminRoute._addFileChildren(AppSettingsAdminRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsAdminRoute: typeof AppSettingsAdminRouteWithChildren
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAdminRoute: AppSettingsAdminRouteWithChildren,
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppPSlugRouteChildren {
  AppPSlugReviewRoute: typeof AppPSlugReviewRoute
  AppPSlugSettingsRoute: typeof AppPSlugSettingsRoute
  AppPSlugIndexRoute: typeof AppPSlugIndexRoute
}

const AppPSlugRouteChildren: AppPSlugRouteChildren = {
  AppPSlugReviewRoute: AppPSlugReviewRoute,
  AppPSlugSettingsRoute: AppPSlugSettingsRoute,
  AppPSlugIndexRoute: AppPSlugIndexRoute,
}

const AppPSlugRouteWithChildren = AppPSlugRoute._addFileChildren(
  AppPSlugRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppIdeasIdeaKeyRoute: typeof AppIdeasIdeaKeyRoute
  AppPSlugRoute: typeof AppPSlugRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppIdeasIdeaKeyRoute: AppIdeasIdeaKeyRoute,
  AppPSlugRoute: AppPSlugRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DesignRoute: DesignRoute,
  LoginRoute: LoginRoute,
  TrackRoute: TrackRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyRoute: VerifyRoute,
  SlugSubmitRoute: SlugSubmitRoute,
  SlugVerifyRoute: SlugVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
